spring:
  #??????
  resources:
    #???????????????
    add-mappings: true
    cache:
      cachecontrol:
        #??????????
        max-age: 3600
    chain:
      #?????????????
      cache: true
      #??????????
      enabled: true
      #???????gzip?brotil????????
      compressed: true
      #??h5?????????
      html-application-cache: true
    static-locations: classpath:/static/

  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      #????????
      idle-timeout: 1800000
      #?????
      maximum-pool-size: 10
      #?????????
      auto-commit: true
      #?????????0??????
      max-lifetime: 1800000
      #??????
      connection-timeout: 3000
      #?????????????
      connection-test-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        #????? ??8
        max-active: 8
        #????????
        max-wait: 1000ms
        #?????????8
        max-idle: 200

  #RabbitMQ
  rabbitmq:
    #???
    host: 127.0.0.1
    #???
    username: guest
    #??
    password: guest
    #????
    virtual-host: /
    #??
    port: 5672
    listener:
      simple:
        #???????
        concurrency: 10
        #???????
        max-concurrency: 10
        #???????????????????????????
        prefetch: 1
        #?????????
        auto-startup: true
        #??????????
        default-requeue-rejected: true
    template:
      retry:
        #???????false
        enabled: true
        #???????1000ms
        initial-interval: 1000ms
        #?????????3?
        max-attempts: 3
        #????????
        max-interval: 10000ms
        #???????????2?0  ???10s ????20s ????40s
        multiplier: 1


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.tuguang.seckill

logging:
  level:
    com.tuguang.sekilldemo.seckill: debug
